print("What is your name?")
ime1 = input()
print("Hello " + ime1)
print("How are you?")
ime2 = input()
print("Bravo. Glad you are " + ime2)
print("What is your favorite food?")
ime3 = input()
print("Yammy! I also like " + ime3)
print("What is your favorite color?")
ime4 = input()
print(ime4 + " is a vary beautiful color!")
